Create session boundary runtime API
paritytech/substrate pull request #10669
Opened 2022-01-14 20:12 UTC by Wizdave97

This PR provides a runtime storage value in the session pallet that holds the block number of when session changes occur. 

This is a companion PR that is required to fix the issue created here https://github.com/paritytech/grandpa-bridge-gadget/issues/256

2022-01-17 08:49 UTC, bkchr requested changes

2022-01-17 08:49 UTC, bkchr commented on primitives/session/src/lib.rs
> +	}
Why is that its own runtime api?

IMO it should just be added to the Beefy runtime api.

2022-01-17 08:49 UTC, bkchr commented on frame/session/src/lib.rs
> +}
Why do we need an extra trait here?

2022-01-17 08:49 UTC, bkchr commented on client/beefy/src/worker.rs
> +				}
```suggestion
				if let Some(session_boundary) = session_boundary {
					metric_set!(self, beefy_best_block, session_boundary);
				}
```

2022-01-17 19:45 UTC, Wizdave97 commented
The polkadot companion has been fixed, the CI checks need to be restarted

2022-01-24 14:05 UTC, acatangiu approved these changes
Looks good!

2022-01-25 11:50 UTC, acatangiu commented
@bkchr please take a look at this PR and its companion, thanks!

2022-02-25 11:26 UTC, seunlanlege commented
Bump

2022-03-28 07:02 UTC, acatangiu commented
Alternative PR https://github.com/paritytech/substrate/pull/10882 merged

2022-03-28 07:02 UTC, closed without merging