Revise how staking configurations are set
paritytech/substrate pull request #10955
Opened 2022-03-01 17:03 UTC by hirschenberger

fixes #10938

polkadot companion: https://github.com/paritytech/polkadot/pull/5018

polkadot address: 1ZApdbwrNnT1Hey4xeTAH6SZPDgbA9ZVftNuu9jTRbkc2Bg

2022-03-01 17:13 UTC, hirschenberger commented
We assume the worst case weight here but it may actually be much more lightweight. 
So it would be possible to refund some weight afterwards.

2022-03-01 18:02 UTC, shawntabrizi approved these changes
lgtm. needs to run weights again after merge

2022-03-02 00:05 UTC, shawntabrizi requested changes
On closer review, actually a few things needs to be patched up:

* You need to make sure all tests pass: `cargo test -p pallet-staking --features runtime-benchmarks`
* Having `ConfigOp<Option<...>>` does not make sense, since `ConfigOp` has all of `Set`, `Remove`, and `Noop`. In the case of `ConfigOp::set(None)`, you probably want to actually do `ConfigOp::Remove`, so really there should be no `Option`s.
* To support options in storage, you can use the `put` api instead of `set` api.
* Add a test that the `put` behavior is working as expected with the underlying storage.
* Look at the tests that you fixed up, and introduce the usage of `ConfigOp::Noop` or `ConfigOp::Remove` where appropriate. For example, if the value does not change from one point to the next.

But the general idea is good, and the way you did weights is good enough imo.

2022-03-02 09:04 UTC, kianenigma commented on frame/staking/src/pallet/mod.rs
> +	#[derive(TypeInfo, Debug, Clone, Encode, Decode, PartialEq)]
```suggestion
	/// Possible operations on the configuration values of this pallet. 	
	#[derive(TypeInfo, Debug, Clone, Encode, Decode, PartialEq)]
```

2022-03-02 09:06 UTC, kianenigma commented on frame/staking/src/tests.rs
> +		assert_eq!(MinCommission::<Test>::get(), Perbill::from_percent(0));
```suggestion
		assert_storage_noop!(Staking::set_staking_configs(
			Origin::root(),
			ConfigOp::Noop,
			ConfigOp::Noop,
			ConfigOp::Noop,
			ConfigOp::Noop,
			ConfigOp::Noop,
			ConfigOp::Noop
		));
```

2022-03-02 09:08 UTC, kianenigma approved these changes
With @shawntabrizi's feedback now it looks good to me! Thanks 💯

2022-03-02 10:46 UTC, shawntabrizi approved these changes

2022-03-02 10:47 UTC, shawntabrizi commented
/tip small

2022-03-02 10:49 UTC, shawntabrizi commented
@hirschenberger are you able to make a companion PR, or do you need help with that?

I would just copy and paste `set_staking_configs` benchmarks, and paste it twice with the appropriate names.

2022-03-02 11:06 UTC, hirschenberger commented
> @hirschenberger are you able to make a companion PR, or do you need help with that?
> 
> I would just copy and paste `set_staking_configs` benchmarks, and paste it twice with the appropriate names.

I can do a companion

2022-03-02 13:45 UTC, hirschenberger commented
/benchmark runtime dev pallet_staking

2022-03-02 13:47 UTC, shawntabrizi commented
/tip small

2022-03-02 13:49 UTC, shawntabrizi commented
/benchmark runtime pallet pallet_staking

2022-03-02 14:58 UTC, shawntabrizi approved these changes

2022-03-03 09:14 UTC, kianenigma commented
bot merge

2022-03-03 09:17 UTC, kianenigma commented
bot merge

2022-03-03 09:17 UTC, merged