[ci] Divide .gitlab-ci.yml into several files
paritytech/substrate pull request #11333
Opened 2022-05-02 13:05 UTC by alvicsam

Attempt to divide `.gitlab-ci.yml` into several files. 
Part of https://github.com/paritytech/ci_cd/issues/325

2022-05-03 15:38 UTC, TriplEight requested changes

2022-05-03 15:38 UTC, TriplEight commented on .gitlab-ci.yml
> +    - !reference [.rust-info-script, script]
this looks a lil' bit ugly for me, but anchors can't be used across files.

2022-05-03 15:38 UTC, TriplEight commented on .gitlab-ci.yml
> +  extends:                         .kubernetes-env
`extends:` has to be used instead of `<<: *anchor-name` notation.
Just documenting here.

2022-05-03 15:38 UTC, TriplEight commented on .gitlab-ci.yml
> +include:
Please write on top of this file that it's been divided into these ones.
And also please add the description on top of each of them.

2022-05-10 14:16 UTC, alvicsam commented
Merge after https://github.com/paritytech/substrate/pull/11384

2022-05-11 08:56 UTC, sergejparity approved these changes

2022-05-11 09:01 UTC, merged