[Do Not Merge] Test gitlab DAG in pipeline
paritytech/substrate pull request #11442
Opened 2022-05-17 13:56 UTC by alvicsam

Part of https://github.com/paritytech/ci_cd/issues/368

2022-05-17 17:27 UTC, TriplEight commented
![image](https://user-images.githubusercontent.com/17856421/168874112-4a96d6a3-09cd-41b3-9d0b-dc3514124853.png)

Please excuse me for this sloppy sketch, this is for reference only.

2022-05-17 17:29 UTC, TriplEight approved these changes
LGTM, good pipelining.
And I see you're using a new feature putting the DAGs into the same stage, t'is good.

2022-05-17 17:36 UTC, TriplEight requested changes
Please also hang a cancel pipeline job to a DAG of:
`cargo-fmt` -> `cargo-clippy` -> `cargo-check-nixos`

Otherwise LGTM, I see you're using a new feature : putting DAGs into the same stage :+1:

2022-05-17 19:36 UTC, alvicsam commented
> Please also hang a cancel pipeline job to a DAG of: `cargo-fmt` -> `cargo-clippy` -> `cargo-check-nixos`

I'm not sure that these jobs should cancel the whole pipeline. The main reason why jobs are in the `cancel-pipeline` needs is that they are `required`. So if they fail it make sense to cancel the whole pipeline. `fmt`, `clippy` and `check-nixos` can be skipped in some circumstances.

2022-05-18 11:04 UTC, sergejparity approved these changes

2022-05-18 11:14 UTC, merged