Improve inspection and generation of node keys
paritytech/substrate pull request #11525
Opened 2022-05-25 17:22 UTC by davxy

Closes https://github.com/paritytech/substrate/issues/11518

---

This PR wants to improve the user experience of `subkey` by expanding a bit the possibilities offered by Substrate `InspectNodeKeyCmd` and `GenerateNodeKeyCmd`.

---

### Node Key Generation.

The command has been extended to allow the user to:
- write the output in binary format (added `--bin` flag)

### Node Key Inspection

The command has been extended to allow the user to:
- read the input in binary format (added `--bin` flag), previously only hex string was allowed. Now is easier to parse node key file under the `network` folder, that when autogenerated is in binary format.
- the file input is now optional (as it is for key generation), if the file is not passed the key is read from stdin.
- some tolerance for whitespaces when input is not binary (trim front/back)

---

The new interface allows more easily to use the commands along with other commands via unix pipes.

For example now is possible to be used like:

```bash
#  writes in bin   |  converts to hex string   |  reads in hex from stdin 
$ subkey generate-node-key --bin | xxd -p -c 32 | subkey inspect-node-key
                           
$ subkey generate-node-key --file secret.out --bin 

$ cat secret.out | subkey inspect-node-key --bin 

$ echo "     07b03b7a2f4bc8e1885b2ae2a51b1fcb96178048ed0ada021f2905c75c5099d4    " | subkey inspect-node-key

etc...
```

---

Additionally the `--network` command has been removed from the `inspect-node-key` option since:
1. it was not used at all
2. it was not used because actually the network type doesn't influence the node-key (i.e. a peer id of libp2p)

2022-05-27 15:04 UTC, kpp commented on client/cli/src/commands/inspect_node_key.rs
> +				io::stdin().lock().read_to_end(&mut buf)?;
read_exact?

2022-05-27 15:17 UTC, kpp requested changes

2022-05-27 15:17 UTC, kpp commented on client/cli/src/commands/inspect_node_key.rs
> +				io::stdin().lock().read_to_end(&mut buf)?;
read_exact

2022-05-27 15:17 UTC, kpp commented on client/cli/src/commands/generate_node_key.rs
> +		eprintln!("Peer-ID: {}", peer_id);
I don't think you should change the format in this PR.

2022-05-27 15:17 UTC, kpp commented on client/cli/src/commands/inspect_node_key.rs
> +		println!("Peer-ID: {}", peer_id);
Same concern about the format of the output.

2022-05-27 15:17 UTC, kpp commented on client/cli/src/commands/inspect_node_key.rs
> +			// With hex input, give to the user a bit of tolerance about whitespaces
Read contents to String and call https://doc.rust-lang.org/stable/std/primitive.str.html#method.trim

2022-05-27 15:17 UTC, kpp commented on client/cli/src/commands/inspect_node_key.rs
> -	pub network_scheme: NetworkSchemeFlag,
Are you sure no one uses it? How about adding a deprecation notice and then gracefully get rid of it?

2022-05-27 18:15 UTC, davxy commented
@kpp thanks for your review. Your points should have been addressed

2022-05-27 23:11 UTC, kpp approved these changes

2022-06-02 10:13 UTC, aardbol commented
Wonderful! Can't really officially review the code since Rust is not my forte :)

2022-06-09 17:55 UTC, merged