Update docker-compose.yml
paritytech/substrate pull request #11802
Opened 2022-07-08 09:48 UTC by lucasvanmol

Fixes #11750

Note that the [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template/blob/9c89be106cb98f4a0ede20d8880ec63779232870/docker-compose.yml#L6) also needs to be updated in the same way.

2022-07-19 08:58 UTC, alvicsam commented
Hi @lucasvanmol , thank you for your PR. Image should be changed to `paritytech/ci-linux:production` because `staging` is updated every night and there are chances that `docker-compose` won't work again. But anyway here `docker-compose up --build` will not work since here is no `Cargo.toml` file. 

Probably `docker-compose.yml` can be removed from here? @NukeManDan wdyt?

I opened a PR with a fix in substrate-node-template: https://github.com/substrate-developer-hub/substrate-node-template/pull/357

2022-08-02 07:18 UTC, alvicsam requested changes

2022-08-02 07:18 UTC, alvicsam commented on bin/node-template/docker-compose.yml
> +    image: paritytech/ci-linux:staging
```suggestion
    image: paritytech/ci-linux:production
```
`paritytech/ci-linux:production` is used in ci pipeline, `staging` can have a newer, not yet supported version of rust

2022-08-02 09:31 UTC, alvicsam approved these changes

2022-08-02 09:47 UTC, ordian approved these changes

2022-08-02 09:59 UTC, alvicsam commented
bot rebase

2022-08-02 11:20 UTC, sergejparity approved these changes

2022-08-02 12:30 UTC, chevdor approved these changes

2022-08-04 07:16 UTC, merged