[DO NOT MERGE] test-linux-stable parallel on 3 ci nodes
paritytech/substrate pull request #11829
Opened 2022-07-13 11:19 UTC by alvicsam

Part of https://github.com/paritytech/ci_cd/issues/207

2022-07-13 15:47 UTC, alvicsam commented
bot rebase

2022-07-14 14:51 UTC, TriplEight commented on scripts/ci/gitlab/pipeline/test.yml
>      # this job runs all tests in former runtime-benchmarks, frame-staking and wasmtime tests
```suggestion
    # this job runs all tests in former runtime-benchmarks, frame-staking and wasmtime tests
    # tests are partitioned by nextest and executed in parallel on $CI_NODE_TOTAL runners
```

2022-07-14 15:03 UTC, alvicsam commented on scripts/ci/gitlab/pipeline/test.yml
> +    CI_JOB_NAME:                   cargo-check-benches
>what is it used for?

need help from @rcny

2022-07-14 15:35 UTC, alvicsam commented on scripts/ci/gitlab/pipeline/test.yml
> +    - if [ ${CI_NODE_INDEX} == 1 ]; then SKIP_WASM_BUILD=1 time cargo +nightly check --benches --all; fi
fixed

2022-07-14 15:50 UTC, alvicsam commented on scripts/ci/gitlab/pipeline/test.yml
> +    CI_JOB_NAME:                   cargo-check-benches
added comment and quotes

2022-07-14 15:56 UTC, TriplEight requested changes

2022-07-14 15:56 UTC, TriplEight commented on scripts/ci/gitlab/pipeline/test.yml
> +        esac
```suggestion
    - echo "___Running benchmarks___";
    - case ${CI_NODE_INDEX} in
        1)
          SKIP_WASM_BUILD=1 time cargo +nightly check --benches --all;
          cargo run --release -p node-bench -- ::trie::read::small --json
            | tee ./artifacts/benches/$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA/::trie::read::small.json;
          echo "___Uploading cache for rusty-cachier___";
          rusty-cachier cache upload
          ;;
        2)
          cargo run --release -p node-bench -- ::node::import::native::sr25519::transfer_keep_alive::paritydb::small --json
            | tee ./artifacts/benches/$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA/::node::import::native::sr25519::transfer_keep_alive::paritydb::small.json
          ;;
        esac
```

2022-07-14 17:01 UTC, radupopa2010 approved these changes

2022-07-15 08:27 UTC, alvicsam commented
@nazar-pc thank you for your suggestion. It'll look nicer but it might be not obvious where details could be found. So now each job has a `details` link which leads to logs for this particular job. With a cumulative check the only thing which I can think of is to put a link to the whole pipeline in `details`. But it might be not clear why this check has failed.

2022-07-15 08:43 UTC, TriplEight approved these changes

2022-07-15 08:44 UTC, merged