feat: generalize ConsensusDataProvider for manual-seal
paritytech/substrate pull request #11827
Opened 2022-07-13 09:31 UTC by yjhmelody

It make manual-seal could handle proof.

BTW, I think the `append_block_import` could be redesign in some other ways for more useful.

2022-07-15 03:33 UTC, yjhmelody commented
Anyone could give me a feedback?

2022-07-28 15:51 UTC, bkchr reviewed
I'm not 100% sure about this, but it looks okay.

Please rename `PROOF` everywhere to `Proof`. Otherwise it looks okay.

2022-07-28 15:51 UTC, bkchr commented on client/consensus/manual-seal/src/consensus/aura.rs
> +impl<B, C, PROOF> ConsensusDataProvider<B> for AuraConsensusDataProvider<B, C, PROOF>
```suggestion
impl<B, C, Proof> ConsensusDataProvider<B> for AuraConsensusDataProvider<B, C, Proof>
```

2022-07-29 08:03 UTC, davxy reviewed
`<Pedantic Mode Nits ON>`
Can we stick to a naming convention for generic parameters?
In some places `P` has been used while in others `Proof` (or `PROOF`).
Generally (not everywhere and if there are no conflicts in names initial letters) we tend to use uppercase single letters or multiple letters for acronyms.
So (IMO) in this case `P` is preferred.
`<Pedantic Mode Nits OFF>`
:-)

2022-07-29 08:16 UTC, yjhmelody commented
> `<Pedantic Mode Nits ON>` Can we stick to a naming convention for generic parameters? In some places `P` has been used while in others `Proof` (or `PROOF`). Generally (not everywhere and if there are no conflicts in names initial letters) we tend to use uppercase single letters or multiple letters for acronyms. So (IMO) in this case `P` is preferred. `<Pedantic Mode Nits OFF>` :-)

Ok, I agree with you.

2022-07-29 09:26 UTC, bkchr commented
> `<Pedantic Mode Nits ON>` Can we stick to a naming convention for generic parameters? In some places `P` has been used while in others `Proof` (or `PROOF`). Generally (not everywhere and if there are no conflicts in names initial letters) we tend to use uppercase single letters or multiple letters for acronyms. So (IMO) in this case `P` is preferred. `<Pedantic Mode Nits OFF>` :-)

I mean we don't use `PROOF` anywhere, this was the reason why I don't wanted to have it. For me there is no fixed threshold, but when the number of generic parameters starts to explode, I switch to use better naming than single characters. 

It is okay and we can keep the pr as is now, but just some note for the future.

2022-07-29 09:26 UTC, bkchr approved these changes

2022-07-29 10:29 UTC, davxy requested changes
@yjhmelody I went through your PR trying to understand why is this required in the first place.

The only motivation that I see is that you have your custom implementation of `ConsensusDataProvider` trait and there you need to use somehow this new associated type `Proof` (e.g. to use your consensus instead of aura and babe).

But from what I can see, the `AuraConsensusDataProvider` and `BabeConsensusDataProvider` implementations doesn't use the introduced generic `P` nor the associated type `Proof` in any useful way. For them, you can just remove `P` and set `Proof` to `()`.

In the end, can you please explain why you need this and eventually change the `Aura` and `Babe` consensus data providers to something like:

```
impl<B, C> ConsensusDataProvider<B> for AuraConsensusDataProvider<C> {
    type Proof = ();
...
}

impl<B, C> ConsensusDataProvider<B> for BabeConsensusDataProvider<B, C> {
    type Proof = ();
...
}
```

2022-07-29 10:46 UTC, yjhmelody commented
@davxy Hi, I want to mock some proof data in manual-seal mode. And maybe I use `aura`, so  `type Proof = ()` is not generic enogh, you know that `basic-authorship` could create `StorageProof`, I may use it.

2022-07-29 11:38 UTC, davxy reviewed
Mmmh I see. So you want to use this additional generic to bind the struct to a specific proof type in case someone/somewhere want to use it.

It just looked a bit awkward because we're not currently actively using it anywhere (in our codebase).

Can't you directly implement the `ConsensusDataProvider` for your mock in order to prevent adding this extra generic param here?

I'm going to remove the blocker, but let's wait a bit for other opinions from @paritytech/sdk-node

2022-07-29 11:38 UTC, davxy commented on client/consensus/manual-seal/src/consensus.rs
> +	type Proof: Send + Sync + 'static;
```suggestion
	/// The proof type.
	type Proof;
```
Bounds not strictly required here

2022-07-29 11:38 UTC, davxy commented on client/consensus/manual-seal/src/consensus/aura.rs
> +	P: Send + Sync + 'static,
```suggestion
	P: Send + Sync,
```
Lifetime bound not strictly required here

2022-07-29 11:38 UTC, davxy commented on client/consensus/manual-seal/src/consensus/babe.rs
> +	P: Send + Sync + 'static,
```suggestion
	P: Send + Sync,
```
Lifetime bound not strictly required here

2022-07-29 11:53 UTC, yjhmelody commented
> Mmmh I see. So you want to use this additional generic to bind the struct to a specific proof type in case someone/somewhere want to use it.
> 
> 
> 
> It just looked a bit awkward because we're not currently actively using it anywhere (in our codebase).
> 
> 
> 
> Can't you directly implement the `ConsensusDataProvider` for your mock in order to prevent adding this extra generic param here?
> 
> 
> 
> I'm going to remove the blocker, but let's wait a bit for other opinions from @paritytech/sdk-node 
yeah，it is fine too

2022-07-29 13:32 UTC, koute commented
> I'm going to remove the blocker, but let's wait a bit for other opinions from @paritytech/sdk-node

Honestly, while having so many generic parameters makes me think that this code should be ~~killed with fire~~ refactored somehow I think adding this seems reasonable, *if there's an actual use case that needs it*. We've already crossed the point of no return way earlier than the 7 generic parameters which one of the functions/types here accept, so one more's not going to make much difference.

2022-07-29 13:41 UTC, davxy approved these changes

2022-07-29 22:07 UTC, bkchr commented
None of this code here is really "important". We also mainly just drag it with us. Meaning if someone needs something, we can add it. As long as the proposed changes are not that crazy or whatever.

2022-07-29 22:07 UTC, merged