rpc: Update jsonrpsee v0.15.1
paritytech/substrate pull request #11939
Opened 2022-07-29 15:28 UTC by lexnv

This PR updates the `jsonrpsee` crate from v0.14.0 to v0.15.1.

### Jsonrpsee Changes
For full list of changes check: [jsonrpsee/releases](https://github.com/paritytech/jsonrpsee/releases)).

- `Middleware` trait has been split into `HttpMiddleware` and `WsMiddleware` to better capture their differences.
- Return error from subscription callbacks for better ergonomics and removed the `PendingSink` concept (you can still manually accept or reject a sink, but otherwise it'll be accepted automatically if you send a message down it).

// cc @jsdw @niklasad1 

### Companions
- Polkadot: TODO
- Cumulus: TODO

2022-07-30 10:47 UTC, niklasad1 commented on client/beefy/rpc/src/lib.rs
> +		assert_eq!(expected_response, response.result,);
```suggestion
		assert_eq!(expected_response, response.result);
```

2022-07-30 10:48 UTC, niklasad1 commented on client/beefy/rpc/src/lib.rs
> +	) -> Result<(), SubscriptionEmptyError> {
can't we use `JsonRpseeError` instead?

2022-07-30 10:50 UTC, niklasad1 commented on client/rpc/src/author/mod.rs
> +			// NOTE: the sink is accepted under the hood for ergonomic purposes.
I think you can stray that note

2022-07-30 10:51 UTC, niklasad1 approved these changes
great LGTM,

as a follow-up we should update the `rpc-api` with the client trait overrides and feature-gate the client stuff such that 
other crates such as subxt can re-use the API definitions from `sc-rpc-api` without having to bring lots needless dependencies such as the `jsonrpsee server stuff`.

2022-08-01 11:13 UTC, jsdw commented
> as a follow-up we should update the rpc-api with the client trait overrides and feature-gate the client stuff such that
other crates such as subxt can re-use the API definitions from sc-rpc-api without having to bring lots needless dependencies such as the jsonrpsee server stuff.

Interesting thought; I added an issue in subxt to point at this. Not sure whether we'd want it or not there yet but worth a thought :) https://github.com/paritytech/subxt/issues/605

2022-08-01 14:09 UTC, jsdw commented on client/rpc/src/state/mod.rs
> +				// NOTE: `SubscriptionEmptyError` is introduced for ergonomic purposes.
is this note just pointing out why we return `Result`s now? Probably not needed (we don't bring it up anywhere else either) :)

2022-08-01 14:10 UTC, jsdw approved these changes
LGTM but let's remove the middleware code duplication :)

2022-08-01 14:22 UTC, niklasad1 commented on Cargo.lock
> +version = "0.82.3"
this is unrelated to jsonrpsee, can you revert it and take care of it another PR?

2022-08-01 14:25 UTC, niklasad1 requested changes
Can you revert the unrelated changes in `Cargo.lock`? 
Lots of unrelated bumps that may cause regressions.

Would be better to take care of that in another PR

2022-08-01 16:11 UTC, niklasad1 approved these changes
:+1:

2022-08-02 17:00 UTC, lexnv commented
bot merge

2022-08-02 17:00 UTC, merged