Integrate automatic update of substrate-node-template
paritytech/substrate pull request #11931
Opened 2022-07-28 13:53 UTC by mordamax

Fix https://github.com/paritytech/opstooling/issues/111
Example of PR: https://github.com/substrate-developer-hub/substrate-node-template/pull/363
Pipeline-script: https://github.com/paritytech/pipeline-scripts/pull/71

2022-07-28 14:16 UTC, alvicsam requested changes

2022-07-28 14:16 UTC, alvicsam commented on scripts/ci/gitlab/pipeline/publish.yml
> +  extends:                         .docker-env
```suggestion
  extends:                         .kubernetes-env
```

2022-07-28 14:19 UTC, alvicsam approved these changes

2022-07-28 15:28 UTC, sergejparity approved these changes

2022-07-29 12:16 UTC, mordamax commented
bot merge

2022-07-29 12:16 UTC, merged