used MaxUnlockingChunks from config
paritytech/substrate pull request #12289
Opened 2022-09-18 10:18 UTC by MrishoLukamba

@kianenigma @ggwpez

2022-09-18 10:20 UTC, MrishoLukamba commented
Solved issue #12227

2022-09-19 09:04 UTC, kianenigma commented
Please follow this syntax to close the linked issue https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.

2022-09-19 09:10 UTC, kianenigma reviewed
You should document in the config type parameter that if this value is ever set, and then decreased, it leads to a corrupt state and a migration is needed. We also need a test to demonstrate this. 

@Ank4n please note that we have the same story with `MaxNominations` as well.

2022-09-20 08:47 UTC, Ank4n commented
@MrishoLukamba Can you also add a test that documents what happens in the scenario where MaxUnlockingChunks is reduced without migration?
Here are couple of examples you can refer
https://github.com/paritytech/substrate/blob/ankan/bound-staking-storage-trivial/frame/staking/src/tests.rs#L4872
https://github.com/paritytech/substrate/blob/ankan/bound-staking-storage-trivial/frame/staking/src/tests.rs#L5367

2022-09-20 08:56 UTC, MrishoLukamba commented
> @MrishoLukamba Can you also add a test that documents what happens in the scenario where MaxUnlockingChunks is reduced without migration? Here are couple of examples you can refer https://github.com/paritytech/substrate/blob/ankan/bound-staking-storage-trivial/frame/staking/src/tests.rs#L4872 https://github.com/paritytech/substrate/blob/ankan/bound-staking-storage-trivial/frame/staking/src/tests.rs#L5367

Okey let me get into it, if anything I will ask

2022-09-22 20:26 UTC, MrishoLukamba commented
@Ank4n @kianenigma There is an issue which I noticed, StakingLedger.staking  BoundedVec does not push new object (UnlockingChunks) instead it just increments the value inside UnlockingChunks. So the MaxUnlockingChunks bound in boundedVec is not quite useful, 
I think is a bug.

2022-09-22 21:04 UTC, Ank4n commented
> @Ank4n @kianenigma There is an issue which I noticed, StakingLedger.staking BoundedVec does not push new object (UnlockingChunks) instead it just increments the value inside UnlockingChunks. So the MaxUnlockingChunks bound in boundedVec is not quite useful, I think is a bug.

Can you elaborate more? May be refer in the code.

I see that when we unbond, a new UnlockChunk is pushed (or UnlockChunk for same era updated).
https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L984

2022-09-23 08:55 UTC, MrishoLukamba commented
> > @Ank4n @kianenigma There is an issue which I noticed, StakingLedger.staking BoundedVec does not push new object (UnlockingChunks) instead it just increments the value inside UnlockingChunks. So the MaxUnlockingChunks bound in boundedVec is not quite useful, I think is a bug.
> 
> Can you elaborate more? May be refer in the code.
> 
> I see that when we unbond, a new UnlockChunk is pushed (or UnlockChunk for same era updated). https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L984

In the code it shows that,a new UnlockChunk is being pushed but in testing it is not pushed it is just updated the value field. So the bound MaxUnlockChunk placed there is not used at all

2022-09-23 11:17 UTC, Ank4n commented
> > > @Ank4n @kianenigma There is an issue which I noticed, StakingLedger.staking BoundedVec does not push new object (UnlockingChunks) instead it just increments the value inside UnlockingChunks. So the MaxUnlockingChunks bound in boundedVec is not quite useful, I think is a bug.
> > 
> > 
> > Can you elaborate more? May be refer in the code.
> > I see that when we unbond, a new UnlockChunk is pushed (or UnlockChunk for same era updated). https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L984
> 
> In the code it shows that,a new UnlockChunk is being pushed but in testing it is not pushed it is just updated the value field. So the bound MaxUnlockChunk placed there is not used at all. You can see in the new test i've added

@MrishoLukamba The behaviour looks correct to me. An `UnlockChunk` is only updated if multiple unbond happen in the same era. If you try to move forward in eras and `unbond`, you should see multiple chunks being added. If the `UnlockChunks` are already full, the transaction should return an error `NoMoreChunks` as the boundedVec is full.

@kianenigma Shouldn't we be able to keep the `MaxUnlockChunk` equal to `BondingDuration`. This will imply users can have `UnlockChunks` without claiming only for up to 28 eras. And in that case all the `UnlockChunks` are ready to be claimed (after 28 eras) so encouraging the user to just claim existing unlocks before requesting for more unlocks.
If you agree with above, we can bound `StakingLedger.unlocking` with `BondingDuration` and not have to introduce a new bound `MaxUnlockChunk`.

2022-09-24 08:19 UTC, kianenigma commented on frame/staking/src/tests.rs
> +		//maxunlockingchunks
```suggestion
```

2022-09-24 08:20 UTC, kianenigma commented on frame/staking/src/tests.rs
> +		for i in 0..<<Test as Config>::MaxUnlockingChunks as Get::<u32>>::get()- 1 {
```suggestion
		for i in 0..<<Test as Config>::MaxUnlockingChunks as Get<u32>>::get()-1 {
```

2022-09-24 08:20 UTC, kianenigma commented on frame/staking/src/tests.rs
> +			<<Test as Config>::MaxUnlockingChunks as Get::<u32>>::get() as usize
```suggestion
			<<Test as Config>::MaxUnlockingChunks as Get<u32>>::get() as usize
```

2022-09-24 08:20 UTC, kianenigma commented on frame/staking/src/tests.rs
> +	//By Default 11, 10 are stash and ctrl and 21,20
```suggestion
	// Concern is on validators only
	// By Default 11, 10 are stash and ctrl and 21,20
```

2022-09-24 08:20 UTC, kianenigma commented on frame/staking/src/tests.rs
> +	//By Default 11, 10 are stash and ctrl and 21,20
Please fix all comments accordingly.

2022-09-24 08:21 UTC, kianenigma requested changes
Logic seems correct, but code needs to be formatted.

2022-09-24 09:39 UTC, MrishoLukamba commented
> Logic seems correct, but code needs to be formatted.

Done, and should i use cargo fmt?

2022-09-24 10:13 UTC, Ank4n commented
@MrishoLukamba I will close this PR and work on top of your code to get it merged. Pls add your Polkadot address in the PR for the tip.

Super thanks for your contribution. Feel free to follow the new PR here: https://github.com/paritytech/substrate/pull/12343

2022-09-24 10:13 UTC, closed without merging

2022-09-24 10:52 UTC, MrishoLukamba commented
> @MrishoLukamba I will close this PR and work on top of your code to get it merged. Pls add your Polkadot address in the PR for the tip.
> 
> Super thanks for your contribution. Feel free to follow the new PR here: #12343

Thanks, will also continue contributing on other issues.

2022-09-24 10:54 UTC, Ank4n commented
/tip small

2022-09-25 08:09 UTC, kianenigma commented
/tip small

2022-09-25 09:54 UTC, MrishoLukamba commented
> /tip small

Sorry @kianenigma @Ank4n https://polkadot.js.org/apps/#/treasury/tips, the tip didnt go through