`seal_reentrant_count` returns contract reentrant count
paritytech/substrate pull request #12695
Opened 2022-11-11 14:25 UTC by Artemka374

This PR addresses [#11082](https://github.com/paritytech/substrate/issues/11082).

2022-11-14 09:06 UTC, athei requested changes
Please address comments.

2022-11-14 09:06 UTC, athei commented on frame/contracts/src/tests.rs
> +fn account_entrance_count_works() {
This test is insufficient:

- It tests only for its own address: Please additionally test for the address of **another** contract on the call stack.
- This only test for the value `1`. Please also test at least for `0`, too.

2022-11-14 17:16 UTC, Artemka374 commented
fixed, please check again

2022-11-15 12:30 UTC, agryaznov approved these changes
LGTM

2022-11-15 13:11 UTC, athei commented on frame/contracts/src/tests.rs
> +fn account_entrance_count_works() {
The test still tests the trivial case where nothing is on the call stack. But let's not be too strict here.

2022-11-15 13:11 UTC, athei approved these changes

2022-11-15 13:12 UTC, merged