[contracts] Add per local weight for function call
paritytech/substrate pull request #12806
Opened 2022-11-29 19:23 UTC by agryaznov

✄ -----------------------------------------------------------------------------

Thank you for your Pull Request! 🙏

Before you submit, please check that:

- [ ] **Description:** You added a brief description of the PR, e.g.:
  - What does it do?
  - What important points should reviewers know?
  - Is there something left for follow-up PRs?
- [ ] **Labels:** You labeled the PR appropriately if you have permissions to do so:
  - [ ] `A*` for PR status (**one required**)
  - [ ] `B*` for changelog (**one required**)
  - [ ] `C*` for release notes (**exactly one required**)
  - [ ] `D*` for various implications/requirements
  - [ ] Github project assignment
- [ ] **Related Issues:** You mentioned a related issue if this PR is related to it, e.g. `Fixes #228` or `Related #1337`.
- [ ] **2 Reviewers:** You asked at least two reviewers to review. If you aren't sure, start with GH suggestions.
- [ ] **Style Guide:** Your PR adheres to [the style guide](https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md)
  - In particular, mind the maximal line length of 100 (120 in exceptional circumstances).
  - There is no commented code checked in unless necessary.
  - Any panickers in the runtime have a proof or were removed.
- [ ] **Runtime Version:** You bumped the runtime version if there are breaking changes in the **runtime**.
- [ ] **Docs:** You updated any rustdocs which may need to change.
- [ ] **Polkadot Companion:** Has the PR altered the external API or interfaces used by Polkadot?
  - [ ] If so, do you have the corresponding Polkadot PR ready?
  - [ ] Optionally: Do you have a corresponding Cumulus PR?

Refer to [the contributing guide](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc) for details.

After you've read this notice feel free to remove it.
Thank you!

✄ -----------------------------------------------------------------------------

2022-11-29 19:49 UTC, agryaznov commented
/cmd queue -c bench-bot $ pallet dev pallet_contracts

2022-11-30 10:10 UTC, athei requested changes

2022-11-30 10:10 UTC, athei commented on frame/contracts/src/schedule.rs
> +	pub call_per_local_cost: u32,
Should be part of `InstructionWeights` as `call_per_local` just next to the other call related costs. Also, by putting it here the derived default impl sets it to `0`.

2022-11-30 10:10 UTC, athei commented on frame/contracts/src/benchmarking/mod.rs
> +	}
We need to find out the cost per instruction. Hence we need a component that allows us to do the linear regression over the number of locals. We can't do `r` at the same time as those influence each other.

```suggestion
	// w_per_local = w_bench
	call_per_local {
		let l in 0 .. T::Schedule::get().limits.locals;
		let mut call_body = body::plain(vec![
				Instruction::End,
		]);
		body::inject_locals(&mut call_body, l);
		let mut sbox = Sandbox::from(&WasmModule::<T>::from(ModuleDefinition {
			call_body: Some(call_body),
			.. Default::default()
		}));
	}: {
		sbox.invoke();
	}
```

2022-11-30 15:24 UTC, athei commented on frame/contracts/src/benchmarking/mod.rs
> +	call_per_local {
```suggestion
	instr_call_per_local {
```

2022-12-01 11:57 UTC, agryaznov commented on frame/contracts/src/benchmarking/mod.rs
> +		let mut sbox = Sandbox::from(&WasmModule::<T>::from(ModuleDefinition {
but won't it generate just the same function body, once it has just an empty instructions set?

2022-12-01 17:20 UTC, athei commented on frame/contracts/src/benchmarking/mod.rs
> +		let mut sbox = Sandbox::from(&WasmModule::<T>::from(ModuleDefinition {
Have a look at the `instr_call` benchmark. It created an additional function and calls it multiple times. This is what needs to be done here.

2022-12-01 18:47 UTC, agryaznov commented
/cmd queue -c bench-bot $ pallet dev pallet_contracts

2022-12-01 20:40 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2108868

2022-12-01 20:40 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2108867

2022-12-01 20:46 UTC, agryaznov commented
/cmd queue -c bench-bot $ pallet dev pallet_contracts

2022-12-02 15:18 UTC, xermicus approved these changes
LGTM

2022-12-06 09:30 UTC, athei approved these changes

2022-12-06 09:52 UTC, athei commented
bot merge

2022-12-06 09:52 UTC, merged