Set WASM_BUILD_WORKSPACE_HINT before starting jobs
paritytech/substrate pull request #12816
Opened 2022-12-01 09:06 UTC by joao-paulo-parity

# Problem

CI jobs currently display warnings such as those ones:

> warning: Could not find `Cargo.lock` for `/builds/parity/mirrors/substrate/bin/node-template/runtime/Cargo.toml`, while searching from `/cargo_target_dir/debug/build/node-template-runtime-f76d399030dc21d7/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.

> warning: Could not find `Cargo.lock` for `/builds/parity/mirrors/substrate/bin/node/runtime/Cargo.toml`, while searching from `/cargo_target_dir/debug/build/kitchensink-runtime-ebd00ce29afae0e3/out`. To fix this, point the `WASM_BUILD_WORKSPACE_HINT` env variable to the directory of the workspace being compiled.

Despite those warnings, the jobs still succeed.

# Solution

Set up `WASM_BUILD_WORKSPACE_HINT="$PWD"` before starting the jobs.

2022-12-01 09:27 UTC, joao-paulo-parity commented
By https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2105754#L1490 I think we need an adjustment for https://github.com/paritytech/pipeline-scripts/blob/1978a96e208a06866396492394b85940ae6a5444/check_dependent_project.sh#L436. Thankfully it's a simple one.

2022-12-01 09:32 UTC, joao-paulo-parity commented
Moving to Draft to prevent accidental merges until https://github.com/paritytech/pipeline-scripts/pull/87 is merged.

2022-12-05 12:50 UTC, bkchr approved these changes

2022-12-05 14:05 UTC, joao-paulo-parity commented
Moving to Draft again because I messed up the variable name in https://github.com/paritytech/pipeline-scripts/pull/87. My bad.

2022-12-08 00:19 UTC, sergejparity approved these changes

2022-12-16 12:06 UTC, alvicsam requested changes

2022-12-16 12:06 UTC, alvicsam commented on scripts/ci/gitlab/pipeline/publish.yml
>      - !reference [.job-switcher, before_script]
```suggestion
```
This on can be removed because it's already in `[.kubernetes-env, before_script]`

2022-12-16 12:09 UTC, alvicsam approved these changes

2022-12-16 12:11 UTC, joao-paulo-parity commented
bot merge

2022-12-16 12:29 UTC, merged