rpc rebase: Try-runtime Revamp and Facelift
paritytech/substrate pull request #12921
Opened 2022-12-13 16:28 UTC by lexnv

This PR merges the `origin/master` into https://github.com/paritytech/substrate/pull/12537.

The main focus of this PR is to handle the new batch request API exposed by the jsonrpsee
in `utils/frame/remote-externalities/src/lib.rs`.

Jsonrpsee changed the API of batch requests and failures are reported via `Err(ErrorObject<'static>)`.

To reflect this change, a new inter-thread messaging is added `BatchFailed`.
Whenever the `BatchFailed` message is encountered, we stop the main waiting loop
and ensure that threads are joined before returning.

Previously, we populated the `pending_ext: &mut TestExternalities`, regardless of the success status.
To eliminate this side effect, if one of the requests from the batch failed
(ie the function returned an error) then the `pending_ext` is left untouched.

2022-12-13 16:49 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2154483

2022-12-13 16:55 UTC, kianenigma commented on utils/frame/remote-externalities/src/lib.rs
> +							.unwrap();
return err?

2022-12-13 17:02 UTC, kianenigma requested changes

2022-12-13 17:02 UTC, kianenigma commented on utils/frame/remote-externalities/src/lib.rs
> -	use std::os::unix::fs::MetadataExt;
why all of these code removals? I think you branched off form the wrong branch. Start from the latest code in my base branch, and merge master please.

2022-12-13 17:17 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2154946

2022-12-13 17:54 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2155321

2022-12-14 12:18 UTC, lexnv commented
bot merge

2022-12-14 12:35 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2157561

2022-12-14 16:59 UTC, merged