Custom origin for staking pallet calls
paritytech/substrate pull request #12943
Opened 2022-12-15 14:41 UTC by Ank4n

Fixes https://github.com/paritytech/substrate/issues/12930

2022-12-17 09:32 UTC, kianenigma commented on frame/staking/src/pallet/mod.rs
> +		type StakingAdminOrigin: EnsureOrigin<Self::RuntimeOrigin>;
This is in the staking pallet, can just be called `AdminOrigin` 😆

2022-12-17 09:33 UTC, kianenigma approved these changes

2022-12-19 00:34 UTC, gpestana approved these changes

2022-12-19 15:29 UTC, lexnv approved these changes

2022-12-22 03:42 UTC, melekes approved these changes

2022-12-23 13:09 UTC, Ank4n commented
Kian raised an issue and I agree that lowering privilege for the critical staking operations like reducing validator count or setting minimum/maximum bounds needs more careful thought. I will make the changes to the PR to only allow slash cancelling and setting minimum commission via `StakingAdmin` origin.

2022-12-25 09:26 UTC, kianenigma requested changes
Needs a rework as per the comment above.

2022-12-25 21:44 UTC, Ank4n commented
Updated PR: https://github.com/paritytech/substrate/pull/13018

2022-12-25 21:44 UTC, closed without merging