Add ethereum pair with keccak_256 hash
paritytech/substrate pull request #13016
Opened 2022-12-24 06:22 UTC by fewensa

✄ -----------------------------------------------------------------------------

Thank you for your Pull Request! 🙏

Before you submit, please check that:

- [x] **Description:** You added a brief description of the PR, e.g.:
  Some chains use Ethereum account style. and use `keccak_256` hash algorithm, like Moonbeam and Darwinia 2.0
  https://github.com/PureStake/moonbeam/blob/214154dbb724ec6c9c97a25d60eb3e74307a45c5/primitives/account/src/lib.rs#L164-L165
  The ecdsa pair is use `keccak_256` hash algorithm. Some clients, such as subxt, will not have a suitable signature algorithm to sign. now the polkadot.js is support this feature https://github.com/polkadot-js/common/blob/7611ec8b014780499a5a1d3b89cf76077d478dea/packages/keyring/src/pair/index.ts#L40
- [ ] **Labels:** You labeled the PR appropriately if you have permissions to do so:
  - [ ] `A*` for PR status (**one required**)
  - [ ] `B*` for changelog (**one required**)
  - [ ] `C*` for release notes (**exactly one required**)
  - [ ] `D*` for various implications/requirements
  - [ ] Github project assignment
- [ ] **Related Issues:** You mentioned a related issue if this PR is related to it, e.g. `Fixes #228` or `Related #1337`.
- [ ] **2 Reviewers:** You asked at least two reviewers to review. If you aren't sure, start with GH suggestions.
- [ ] **Style Guide:** Your PR adheres to [the style guide](https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md)
  - In particular, mind the maximal line length of 100 (120 in exceptional circumstances).
  - There is no commented code checked in unless necessary.
  - Any panickers in the runtime have a proof or were removed.
- [ ] **Runtime Version:** You bumped the runtime version if there are breaking changes in the **runtime**.
- [ ] **Docs:** You updated any rustdocs which may need to change.
- [ ] **Polkadot Companion:** Has the PR altered the external API or interfaces used by Polkadot?
  - [ ] If so, do you have the corresponding Polkadot PR ready?
  - [ ] Optionally: Do you have a corresponding Cumulus PR?

Refer to [the contributing guide](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc) for details.

After you've read this notice feel free to remove it.
Thank you!

✄ -----------------------------------------------------------------------------

2022-12-24 06:35 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2195668

2022-12-26 08:44 UTC, fewensa commented on primitives/core/src/ethereum.rs
> +	("Secp256k1HDKD", secret_seed, cc).using_encoded(sp_core_hashing::blake2_256)
I'm not sure here. keep using `blake2_256`?

2022-12-26 08:53 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2197365

2022-12-26 09:21 UTC, davxy commented
The difference between `ecdsa.rs` and `ethereum.rs` is really few lines, i.e. only the hashing algorithm (blake2 end keccak, respectively). I'm not sure this huge code verbatim duplication is the right way to eventually introduce this.

Even the naming of these two objects looks wrong to me, these in the end are just `ecdsa+secp256k1+hash` where has is `keccak` or `blake`.

If we really need to introduce this new pair type in our codebase, a good approach IMO is to make the code in  `ecdsa.rs` generic over the hash (and maybe in the future over the curve as well... but now is not necessary). Then have two specializations (in the same source file), one using keccak and one using blake2. And obviously create two separate `CryptoTypeId` as well.

2022-12-26 09:21 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2197459

2022-12-26 09:23 UTC, davxy requested changes
The difference between the code in `ecdsa.rs` and `ethereum.rs` is really few lines, i.e. only the hashing algorithm (blake2 end keccak, respectively). I'm not sure this huge code verbatim duplication is the right way to eventually introduce this.

Even the naming of these two objects looks wrong to me, these in the end are just ecdsa+secp256k1+hash where has is keccak or blake.

If we really need to introduce this new key pair type directly in our codebase, a better approach IMO is to make the code in `ecdsa.rs` generic over the hash (and maybe in the future over the curve as well... but now is not necessary). Then have two specializations (in the same source file), one using keccak and one using blake2. And obviously create two separate `CryptoTypeId` as well.

2022-12-26 14:20 UTC, fewensa commented
> The difference between the code in `ecdsa.rs` and `ethereum.rs` is really few lines, i.e. only the hashing algorithm (blake2 end keccak, respectively). I'm not sure this huge code verbatim duplication is the right way to eventually introduce this.
> 
> Even the naming of these two objects looks wrong to me, these in the end are just ecdsa+secp256k1+hash where has is keccak or blake.
> 
> If we really need to introduce this new key pair type directly in our codebase, a better approach IMO is to make the code in `ecdsa.rs` generic over the hash (and maybe in the future over the curve as well... but now is not necessary). Then have two specializations (in the same source file), one using keccak and one using blake2. And obviously create two separate `CryptoTypeId` as well.

Yes, agree with you. I can refactor it if the idea is feasible.

2022-12-26 15:02 UTC, bkchr commented
Sounds like a good idea by @davxy

2023-01-05 04:19 UTC, fewensa commented
Hi @davxy , I have a question there.

I have tried to add a generic type to `Signature` and Pair to support different hashing. but the `Signature` struct has `PassByInner` macro. 
https://github.com/fewensa/substrate/commit/09c5afd4b55a19f7515475fd383db0edb9cf8630#diff-a1370f23ed063d050c75648f95fc2811b04b9c04203376f24c2f7e99b00b800bR209-R212

https://github.com/paritytech/substrate/blob/ea387c634715793f806286abf1e64cabf9b7026f/primitives/runtime-interface/proc-macro/src/pass_by/inner.rs#L98

I think we can not remove `if unnamed.unnamed.len() == 1` in `PassByInner` macro.
If not use the generic method, here’s how to add a transitive hashing algorithm. otherwise, only add different struct here to make the difference between hashing algorithms

2023-01-05 08:49 UTC, bkchr commented
@fewensa you can also implement the trait manually.

2023-01-06 08:05 UTC, closed without merging