Fix try-runtime with create-snapshot
paritytech/substrate pull request #13223
Opened 2023-01-23 22:37 UTC by zjb0807

run the `create-snapshot`  command in Polkadot will get an error:
```
cargo run --features try-runtime -- try-runtime --runtime existing create-snapshot --uri wss://rpc.polkadot.io:443 --pallet indices
```

```
Invalid input: given runtime is NOT compiled with try-runtime feature!
```

<img width="992" alt="image" src="https://user-images.githubusercontent.com/16496415/214149937-ff181c04-4558-478e-942a-841197bc7d06.png">

2023-01-24 12:56 UTC, bkchr requested changes

2023-01-24 12:56 UTC, bkchr commented on utils/frame/try-runtime/cli/src/lib.rs
> +		command: &Command,
I don't get why you make it so complicated? You can just pass some `ensure_try_runtime: bool` and everything passes `true`, but not `create_snapshot`.

2023-01-24 15:40 UTC, bkchr approved these changes

2023-01-25 22:12 UTC, Ank4n approved these changes

2023-01-25 23:12 UTC, merged