[contracts] Add upfront weight of merkle trie proofs for storage reading functions
paritytech/substrate pull request #13236
Opened 2023-01-24 20:17 UTC by agryaznov

Follow-up to https://github.com/paritytech/substrate/pull/12976

Even for a single-byte reading operation, proofs of all merkle trie hashes would apparently be needed. Hence this static weight is added to all the storage reading functions.

2023-01-24 22:05 UTC, athei approved these changes

2023-01-25 14:16 UTC, xermicus approved these changes

2023-01-25 14:39 UTC, athei requested changes
Blocking merge for now. We want to fix up the schedule printing macro here before merge.

2023-01-25 14:51 UTC, agryaznov commented
> We want to fix up the schedule printing macro here before merge.

fixed

2023-01-25 18:12 UTC, merged