Only assert events in `assert_*` functions
paritytech/substrate pull request #13244
Opened 2023-01-26 15:13 UTC by ggwpez

Turns out we call this function in some Polkadot benchmarks and it makes them panic. Putting this check only in the explicit functions makes more sense anyway IMO and fixes that.

Failing CI example https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2320642

2023-01-26 16:13 UTC, kianenigma approved these changes

2023-01-26 17:08 UTC, bkchr requested changes
The benchmark is failing here: https://github.com/paritytech/polkadot/blob/38c820b260284e615e7184d4f38696b063cceb8a/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs#L104

Which is not used? 

And the general solution should be to fix the benchmark to switch to block 1 instead of changing this code here.

2023-01-26 19:32 UTC, ggwpez commented
>The benchmark is failing here:

Yea, actually the benchmark *test* is failing.

>And the general solution should be to fix the benchmark to switch to block 1 instead of changing this code here.

IMO it is a bit unexpected when `System::events()` panics instead of returning nothing, but I can also change the bench.

2023-01-26 19:40 UTC, ggwpez commented
Okay here https://github.com/paritytech/polkadot/pull/6635 @bkchr

2023-01-26 19:40 UTC, closed without merging

2023-02-14 23:03 UTC, ggwpez commented
@conatus-est @marebranza please look into work chat to prevent your account from being removed from the org.