feat: renamed ensure_none to unsure_unsigned
paritytech/substrate pull request #13294
Opened 2023-02-02 08:06 UTC by gitofdeepanshu

Fix #13279 
## Description
Renamed FRAME System's `ensure_none` to `ensure_unsigned`

2023-02-02 08:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2343453

2023-02-02 08:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2343452

2023-02-02 08:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2343451

2023-02-02 08:51 UTC, xlc requested changes
Please don't just break common API without notice.
You need to kept `ensure_none` alias and mark it as `#[deprecated]`.

2023-02-02 09:36 UTC, gitofdeepanshu commented
> Please don't just break common API without notice. You need to kept `ensure_none` alias and mark it as `#[deprecated]`.

Added 'ensure_none' alias as requested by @xlc .

2023-02-02 09:40 UTC, gitofdeepanshu commented
btw is it just me or does it take 30 minutes for everyone to build?

2023-02-02 09:59 UTC, ggwpez commented
> btw is it just me or does it take 30 minutes for everyone to build?

Building the whole thing can take a while without Sccache and fast hardware. Normally compiling a few singluar crates + CI checks works good. I often just do `cargo c -p pallet-balances` or whatever for small changes.

Please update the description to mention the alias and that this is *not* a breaking change.

2023-02-03 08:31 UTC, gitofdeepanshu commented
> Please update the description to mention the alias and that this is _not_ a breaking change.

Done.
Although local CI checks are passing, Polkadot CI is failing. `ensure_none` still exists but Polkadot can't seem to find it.

2023-02-03 13:11 UTC, ggwpez commented on frame/system/src/lib.rs
> -	pub use crate::{ensure_none, ensure_root, ensure_signed, ensure_signed_or_root};
You still have to export it, otherwise this is a braking change and Polkadot will not find it anymore.

2023-02-03 13:14 UTC, ggwpez commented on frame/system/src/lib.rs
> +/// Now Deprecated, Use `ensure_unsigned` instead
I dont get this comment. The function did not change. Why do you now mention `root`?

2023-02-03 13:15 UTC, ggwpez commented on frame/system/src/lib.rs
> +#[deprecated]
```suggestion
#[deprecated(note = "Renamed to 'ensure_unsigned' as clarification")]
```

2023-02-04 08:09 UTC, davxy commented
IMO the naming now may be more misleading than before.

We have an enum:
```
pub enum RawOrigin<AccountId> {
    Root,
    Signed(AccountId),
    None,
}
```

Currently there is a check function for each variant (where the name of the function is in 1 to 1 correspondence to the variant name)... Pretty easy
- `ensure_signed` <-> `Signed<T>`
- `ensure_root` <-> `Root`
- `ensure_none` <-> `None`

As a user of `ensure_unsigned` I may logically  (wrongly) infer that `ensure_unsigned` is the opposite of `ensure_signed`. 
But it is not. Since Root is not allowed by both of them. 

In short, `ensure_signed(org) || ensure_unsigned(org)` is not a tautology as one may expect.

Obviously reading the docs removes any doubt. But the same applies for the previous implementation

2023-02-04 08:13 UTC, davxy reviewed
IMO the naming now may be more misleading than before.

We have an enum:
```
pub enum RawOrigin<AccountId> {
    Root,
    Signed(AccountId),
    None,
}
```

Currently there is a check function for each variant (where the name of the function is in 1 to 1 correspondence to the variant name)... Pretty easy
- `ensure_signed` <-> `Signed<T>`
- `ensure_root` <-> `Root`
- `ensure_none` <-> `None`

As a user of the new `ensure_unsigned` I may logically  (wrongly) infer that `ensure_unsigned` is the opposite of `ensure_signed`. 
But it is not, since `Root` origin is not allowed by both of them. 

In short, `ensure_signed(org) || ensure_unsigned(org)` is not a tautology as one may expect.

Obviously reading the docs removes any doubt. But the same "read the docs" approach applies to the previous implementation as well

2023-02-06 10:28 UTC, bkchr commented
> As a user of the new `ensure_unsigned` I may logically (wrongly) infer that `ensure_unsigned` is the opposite of `ensure_signed`.
> But it is not, since `Root` origin is not allowed by both of them.

While this is true, you could not assume that `ensure_none` is meaning "no one can call this". And also nothing bad would be happen if you use `ensure_unsigned` and it is called with `Root`.

I think the general direction is fine, but we should also rename `None` in the enum `RawOrigin` to `Unsigned`. There are also usages of `none` like here: https://github.com/paritytech/substrate/blob/f5e370da7f34622637a343f03420b4242b321891/frame/support/src/traits/dispatch.rs#L349-L350 

So, if we do it, we should do it everywhere and use `deprecated` where possible.

2023-03-22 17:29 UTC, closed without merging

2023-05-17 09:56 UTC, juangirini commented
@gitofdeepanshu would you take this issue over?