sc-client-db: Fix `PruningMode::ArchiveCanonical`
paritytech/substrate pull request #13361
Opened 2023-02-10 14:50 UTC by bkchr

When running a node with `--state-pruning archive-canonical` it was directly failing on genesis. There was an issue in the state-db `pin` implementation. It was not checking the state of a block correctly when running with archive canonical (and also not for every other block after they are canonicalized).

Closes: https://github.com/paritytech/substrate/issues/12824
Closes: https://github.com/paritytech/substrate/issues/13269

2023-02-12 17:26 UTC, melekes approved these changes
👍

2023-02-13 10:02 UTC, arkpar requested changes

2023-02-13 10:52 UTC, bkchr commented on client/db/src/lib.rs
> +	fn empty_state(&self) -> RecordStatsState<RefTrackingState<Block>, Block> {
It is not needed, but nothing inside this function is returning an error. Aka it is infallible.

2023-02-13 10:52 UTC, bkchr commented on client/state-db/src/lib.rs
> +						None => IsPruned::MaybePruned,
We never call this code in the db when we have `PruningMode::ArchiveCanonical | PruningMode::ArchiveAll`. However, I wanted to make it correct when someone may calls this function in the future. `self.pruning` is always set when have `PruningMode::Constrained`. 
If the pruning isn't set, we can not know if the value is pruned or not in here. When this is some block of a stale fork before the finalized block `NotPruned` wouldn't be correct for `ArchiveCanonical`

2023-02-13 11:38 UTC, arkpar commented on client/db/src/lib.rs
> +	fn empty_state(&self) -> RecordStatsState<RefTrackingState<Block>, Block> {
Right, I misread the change

2023-02-13 11:38 UTC, arkpar approved these changes

2023-02-13 11:39 UTC, arkpar commented
bot merge

2023-02-13 11:39 UTC, merged

2023-03-09 19:30 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-39/2277/1