basic nix support, builds subkey and provides it to other packages
paritytech/substrate pull request #13713
Opened 2023-03-25 17:56 UTC by dzmitry-lahoda

Basic nix support.
  
- What does it do? 

Builds subkey via nix

- What important points should reviewers know? 

`nix run .#subkey`, ensure flakes enabled (zero to nix installer is default)

Is there something left for follow-up PRs?
no follow up, so may build other tools if there are later

other usage of nix can be seen here https://github.com/paritytech/zombienet for example

2023-03-25 19:04 UTC, ggwpez commented
Nix usage in the past had the problem that is was got out-dated since there was no CI to check that it still builds.  
Maybe a good follow-up would be to add that.

2023-03-27 10:11 UTC, ggwpez commented
> @ggwpez i am not agains CI PR sure, but that could be out of scope for Parity to merge it now? so nixified subkey tool is nice regardless imho. you can onliner it it on nixos ;)

Yes sure it is out of scope.  

I personally dont use nix/flake, so cant approve. But maybe @bkchr can :smile:

2023-04-09 22:48 UTC, bkchr approved these changes

2023-05-17 22:07 UTC, andresilva requested changes
Thanks for the PR and really sorry for this not getting merged sooner. I started making some suggestions but they became too much to add here, so here's a commit with all my proposed changes: https://github.com/paritytech/substrate/commit/77be00ab11642c412c6eaa26e54b4ca64cc4f0c3. Some are just style nits, but some other changes make the definition simpler (like using `bindgenHook` instead of manually setting up clang), feel free to include whatever you think makes sense.

2023-05-17 22:07 UTC, andresilva commented on flake.nix
> +            rustc = pkgs.rust-bin.beta.latest.default;
stable works as well, and we could even use the rust toolchain from nixpkgs directly (that's I use to build subkey on my computer).

2023-05-26 10:25 UTC, andresilva approved these changes

2023-05-26 10:28 UTC, andresilva commented
@dzmitry-lahoda could you fix the conflicts so that this can be merged? I can't push to your branch.

2023-07-09 17:34 UTC, closed without merging