contracts: add sr25519_recover
paritytech/substrate pull request #13724
Opened 2023-03-27 15:35 UTC by pgherveou

✄ -----------------------------------------------------------------------------

Thank you for your Pull Request! 🙏

Before you submit, please check that:

- [ ] **Description:** You added a brief description of the PR, e.g.:
  - What does it do?
  - What important points should reviewers know?
  - Is there something left for follow-up PRs?
- [ ] **Labels:** You labeled the PR appropriately if you have permissions to do so:
  - [ ] `A*` for PR status (**one required**)
  - [ ] `B*` for changelog (**one required**)
  - [ ] `C*` for release notes (**exactly one required**)
  - [ ] `D*` for various implications/requirements
  - [ ] Github project assignment
- [ ] **Related Issues:** You mentioned a related issue if this PR is related to it, e.g. `Fixes #228` or `Related #1337`.
- [ ] **2 Reviewers:** You asked at least two reviewers to review. If you aren't sure, start with GH suggestions.
- [ ] **Style Guide:** Your PR adheres to [the style guide](https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md)
  - In particular, mind the maximal line length of 100 (120 in exceptional circumstances).
  - There is no commented code checked in unless necessary.
  - Any panickers in the runtime have a proof or were removed.
- [ ] **Runtime Version:** You bumped the runtime version if there are breaking changes in the **runtime**.
- [ ] **Docs:** You updated any rustdocs which may need to change.
- [ ] **Polkadot Companion:** Has the PR altered the external API or interfaces used by Polkadot?
  - [ ] If so, do you have the corresponding Polkadot PR ready?
  - [ ] Optionally: Do you have a corresponding Cumulus PR?

Refer to [the contributing guide](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc) for details.

After you've read this notice feel free to remove it.
Thank you!

✄ -----------------------------------------------------------------------------

2023-03-27 15:56 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2596313

2023-03-29 23:11 UTC, pgherveou commented
bot bench $ pallet dev pallet_contracts

2023-03-29 23:27 UTC, pgherveou commented on frame/contracts/src/weights.rs
missing the actual benchmark to generate this. working on it

2023-03-30 08:39 UTC, pgherveou commented
@athei  quicks questions, before I take a second pass at this:

- should we implement a generic verify function as demonstrated here
https://github.com/AstarNetwork/astar-frame/pull/141/files#diff-16c73d79bacd21e8243b65478b218afa791cb812008c4f8055a549d03cd4862a

- Not too sure what are the exact use cases here, but do we want the message payload to be hashed so it's constant size or 
should it just be an arbitrary payload

2023-03-30 18:37 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2622226

2023-03-30 18:37 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2622212

2023-03-31 13:20 UTC, athei reviewed
> should we implement a generic verify function as demonstrated here
> https://github.com/AstarNetwork/astar-frame/pull/141/files#diff-16c73d79bacd21e8243b65478b218afa791cb812008c4f8055a549d03cd4862a

I would say we opt for individual host functions. We don't have precedence for multiplexed functions. Reason is that it makes benchmarking harder when we multiplex: The weight will depend on the argument which decides which algorithm to depley. Hence this PR should a function for sr25519 and one for ed25519.

> Not too sure what are the exact use cases here, but do we want the message payload to be hashed so it's constant size or
> should it just be an arbitrary payload

The message will be an arbitrary payload as demonstrated in this PR. Reason is that this is what the functions in `sp_io::crypto` expect. Weight needs to be linear over its length.

2023-03-31 13:20 UTC, athei commented on frame/contracts/src/exec.rs
> +	crypto::{secp256k1_ecdsa_recover_compressed, sr25519_verify as crypto_sr25519_verify},
I don't think we need the rename. Our function is scoped within the trait.

```suggestion
	crypto::{secp256k1_ecdsa_recover_compressed, sr25519_verify},
```

2023-03-31 13:20 UTC, athei commented on frame/contracts/src/wasm/runtime.rs
> +	Sr25519Verify,
Cost is not constant but linear over the message length.

2023-04-03 12:40 UTC, agryaznov requested changes

2023-04-03 12:40 UTC, agryaznov commented on frame/contracts/src/wasm/mod.rs
> +		fn sr25519_verify(&self, signature: &[u8; 64], message: &[u8], pub_key: &[u8; 32]) -> bool {
we need to add test here as well, on the mocked Ext, see below for examples

2023-04-03 12:40 UTC, agryaznov commented on frame/contracts/src/wasm/runtime.rs
> +	#[prefixed_alias]
```suggestion
	#[unstable]
	#[prefixed_alias]
```
new functions not covered with e2e tests should be marked _unstable_

2023-04-03 12:40 UTC, agryaznov commented on frame/contracts/src/tests.rs
> +		assert!(call_with_message(&b"hello worlD").is_err());
let's check the returned err code here

2023-04-03 12:40 UTC, agryaznov commented on frame/contracts/fixtures/sr25519_verify.wat
> +		;; trap if the result is not 0x0 (false)
```suggestion
		;; trap if the result is not 0x0 (ReturnCode::Success)
```

2023-04-03 13:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634133

2023-04-03 13:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634132

2023-04-03 13:09 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634147

2023-04-04 20:30 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642853

2023-04-04 20:30 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642852

2023-04-04 20:33 UTC, pgherveou commented
oups bad merge, fixing it now

2023-04-04 20:34 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642925

2023-04-04 20:34 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642924

2023-04-04 20:39 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642978

2023-04-04 20:39 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642977

2023-04-04 20:41 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2643029

2023-04-04 20:41 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2643030

2023-04-04 22:53 UTC, pgherveou commented on frame/contracts/fixtures/sr25519_verify.wat
> +;; 3) Traps if the signature is invalid
```suggestion
;; 2) Calls and return the result of sr25519_verify
```

2023-04-04 23:03 UTC, pgherveou commented
bot bench $ pallet pallet_contracts

2023-04-05 05:18 UTC, pgherveou commented on frame/contracts/src/benchmarking/mod.rs
> +	// `n`: Messaqe input to verify in bytes
```suggestion
	// `n`: Message input to verify in bytes
```

2023-04-05 05:22 UTC, pgherveou commented
bot bench $ pallet pallet_contracts

2023-04-05 05:22 UTC, pgherveou commented
bot cancel

2023-04-05 05:23 UTC, pgherveou commented
bot bench $ pallet dev pallet_contracts

2023-04-05 05:26 UTC, pgherveou commented on frame/contracts/fixtures/sr25519_verify.wat
> +	;; [4, 8) len of signature + message + public key - 64 + 12 + 32 = 108 bytes
```suggestion
	;; [4, 8) length of signature + message + public key - 64 + 12 + 32 = 108 bytes
```

2023-04-05 05:30 UTC, pgherveou commented on frame/contracts/src/wasm/runtime.rs
> +	/// # Errors
```suggestion
    ///
	/// # Errors
```

2023-04-05 05:33 UTC, pgherveou commented on frame/contracts/src/benchmarking/mod.rs
> +	// `n`: Message input to verify in bytes.
```suggestion
	// `n`: Message input length to verify in bytes.
```

2023-04-05 06:43 UTC, pgherveou commented
bot bench $ pallet pallet_contracts

Note to self do not commit until jobs done

2023-04-05 07:35 UTC, pgherveou commented
bot bench $ pallet pallet_contracts

2023-04-05 09:44 UTC, pgherveou commented
bot bench $ pallet dev pallet_contracts

2023-04-05 19:05 UTC, athei commented on frame/contracts/fixtures/sr25519_verify.wat
> +	(data (i32.const 4) "\6c")
`0` is a valid address in wasm. Maybe I am missing something but I can't see a reason to start at `4` rather than zero.

2023-04-05 19:43 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2650245

2023-04-06 10:10 UTC, pgherveou commented on frame/contracts/src/wasm/runtime.rs
> +			ctx.read_sandbox_memory_as_unbounded(memory, message_ptr, message_len)?;
ah nvm understood what you mean

2023-04-06 12:25 UTC, pgherveou commented
bot bench $ pallet dev pallet_contracts

2023-04-06 13:05 UTC, pgherveou commented
bot bench $ pallet dev pallet_contracts

2023-04-06 13:11 UTC, oleg-plakida commented
> @pgherveou Command `"$PIPELINE_SCRIPTS_DIR/commands/bench/bench.sh" pallet dev pallet_contracts` has finished. Result: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2653407 has finished. If any artifacts were generated, you can download them from https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2653405/artifacts/download.

It's not finished. I've restarted the job.

2023-04-07 05:49 UTC, pgherveou commented on frame/contracts/fixtures/sr25519_verify.wat
> +		;; up to 108 bytes stored at offset 0
```suggestion
		;; up to 107 bytes stored at offset 0
```

2023-04-07 05:50 UTC, pgherveou commented on frame/contracts/fixtures/sr25519_verify.wat
> +	;; write the length of the input (107 bytes) at offset 0
```suggestion
	;; write the length of the input (6b = 107) bytes at offset 0
```

2023-04-07 05:57 UTC, pgherveou commented on frame/contracts/src/wasm/runtime.rs
> +	/// Weight of calling `seal_sr25519_verify` for the given input length.
```suggestion
	/// Weight of calling `seal_sr25519_verify` for the given input size.
```

2023-04-07 06:00 UTC, pgherveou commented on frame/contracts/src/wasm/runtime.rs
> +	///   decodable as a Scale encoded Vec<u8>. Traps otherwise
```suggestion
	/// - `message_ptr`: the pointer into the linear memory where the message is placed.
```

2023-04-07 14:11 UTC, pgherveou commented on frame/contracts/src/benchmarking/mod.rs
> +		let message = b"Hello world".to_vec().encode();
```suggestion
		let message = b"Hello world".to_vec();
```

2023-04-07 14:12 UTC, pgherveou commented on frame/contracts/src/benchmarking/mod.rs
> +		let message = (0..n).zip((32u8..127u8).cycle()).map(|(_, c)| c).collect::<Vec<_>>().encode();
```suggestion
		let message = (0..n).zip((32u8..127u8).cycle()).map(|(_, c)| c).collect::<Vec<_>>();
```

2023-04-12 13:43 UTC, athei approved these changes

2023-04-12 13:44 UTC, agryaznov approved these changes
only nitpicks

2023-04-12 14:14 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2673478

2023-04-12 14:40 UTC, pgherveou commented
bot merge

2023-04-12 14:49 UTC, merged

2023-05-02 08:44 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/april-updates-for-substrate-and-polkadot-devs/2764/1