Deprecates the `chill` extrinsic in staking
paritytech/substrate pull request #14187
Opened 2023-05-22 11:06 UTC by gpestana

This PR refactors the `chill` and `chill_other` extrinsics in staking. The current `chill` extrinsic can be deprecated in lieu of `chill_other`, since the logic of `chill` is a subset of `chill_other`

**Changes**:
1. Removes `chill_other` extrinsic
2. Refactors `chill` so that callers can chill own or third-party controller.  The caller can pass a optional controller account ID, which has the same logic as the current `fn chill_other`

```rust
pub fn chill(
  origin: OriginFor<T>,
  controller: Option<T::AccountId>,
) -> DispatchResultWithPostInfo
``` 

Closes https://github.com/paritytech/substrate/issues/9111

2023-05-22 12:31 UTC, Ank4n commented on frame/staking/src/pallet/mod.rs
> +				// caller controlls the controller.
Seems comment is not correct. I believe this condition is to check if Nominator Preference is undecodeable?

2023-05-25 10:12 UTC, juangirini requested changes
These are breaking changes for anything using the old `chill` or `chill_other`. I suggest to follow the deprecation process proposed [here](https://github.com/paritytech/substrate/issues/13976).
I have updated the [issue description](https://github.com/paritytech/substrate/issues/9111) to track this deprecation process.
In this context we need to keep both extrinsics, but replace any reference to `chill` in favour of `chill_other`.
In another PR, once we have confirmed that any examples or tutorials (if any) have been updated, we should add a deprecation warning to `chill` saying that `chill_other` should be used instead. This deprecation will be noted in the release log.
Only afterwards we should be good to delete `chill`, and eventually rename `chill_other` to `chill`.

2023-05-27 22:03 UTC, gpestana commented
I'm closing this PR for now as after a few discussions, we think that it's better to avoid having another breaking change in the API at this point. Since this deprecation is mostly cosmetic, let's pause it for now and wait until we have a more stable deprecation process in place.

2023-05-27 22:03 UTC, closed without merging

2023-05-30 14:39 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/stablising-v15-metadata/2819/9