let `initialize` function in `pallet-grandpa`/`pallet-babe` and other session managed pallets be `pub`
paritytech/substrate pull request #14556
Opened 2023-07-12 07:36 UTC by atenjin

close #14555

In this pr, we hope to let those function be `pub`, which is called under `OneSessionHandler::on_genesis_session` function.

More details pleases refers to issue #14555

2023-07-20 08:37 UTC, davxy commented
see https://github.com/paritytech/substrate/issues/14555#issuecomment-1643455714

2023-07-20 16:28 UTC, sam0x17 submitted a review, later dismissed

2023-07-20 17:15 UTC, davxy requested changes
Before merge I'd like to have an opinion on https://github.com/paritytech/substrate/issues/14555#issuecomment-1643455714

2023-08-19 11:01 UTC, KiChjang commented
Think we should close this; existing issue still has an unanswered comment, and it isn't clear yet that this PR is doing the right thing.

2023-08-19 11:01 UTC, closed without merging