Contracts: expose charge_storage to chain_extension
paritytech/substrate pull request #14712
Opened 2023-08-04 13:52 UTC by pgherveou

2023-08-05 14:02 UTC, athei requested changes
We need to re-export `Diff` so that the type can be constructed. Best to do that from `chain_exntension`.

2023-08-06 19:13 UTC, athei approved these changes

2023-08-17 13:36 UTC, agryaznov approved these changes

2023-08-17 13:37 UTC, pgherveou commented
bot merge

2023-08-17 13:37 UTC, merged