GeekCash reserve SS58 address id 19
paritytech/substrate pull request #7195
Opened 2020-09-24 08:35 UTC by nasa8x

Hello,

This PR adds a new ss58 address 19 for GeekCash network.

Thank you!

2020-09-24 14:45 UTC, bkchr requested changes
Could you please also update the `ss58registry.json` file in the top level directory

2020-09-25 01:31 UTC, nasa8x commented
I've updated. Thank you.

2020-09-29 08:03 UTC, bkchr approved these changes

2020-09-29 08:03 UTC, bkchr commented
@nasa8x please merge master and after that I will merge the pr. Thank you

2020-09-29 12:12 UTC, merged