WIP: Validator dampening
paritytech/substrate pull request #7231
Opened 2020-09-29 08:52 UTC by g2udevelopment

This PR build on top of the previous work of @shawntabrizi. It implements the features in #6997. 
It also adds a flag to turn on/off the use of the dampening function and it adds an extra MaxValidatorCount storage item.
On top of that I added mocks and a few tests, to test the basic functioning of the dampening function.

I think a few test could be added so it would be helpfull if someone can add them. Also validation of the rules is still needed.

2020-09-29 13:14 UTC, kianenigma requested changes
I disagree with the logic of validator count update being baked into staking. 

With `ValidatorCountAdjust `, you allow a user of substrate to opt out of this feature, which is good. But what if someone wants to have some update function, like the one proposed for kusama, but slightly different? this won't be possible with your API. 

As recommended, I think having a `type ValidatorConvert: Convert<u32, u32>`. For a chain that wants to opt out, they will pass in an `IdentityConvert` which doesn't touch the count. Kusama can have its own custom implementation, and an other chain is free to customize this.

2020-09-29 13:16 UTC, kianenigma commented on frame/staking/src/lib.rs
> +	fn update_target_validators(mut exposures: Vec<BalanceOf<T>>) -> u32 {
the name exposure should ideally refer to the type `Exposure`, maybe call this `exposed_balances`

2020-09-29 13:17 UTC, kianenigma commented on frame/staking/src/lib.rs
> +			}) / BalanceOf::<T>::saturated_from(all.len() as u128)
I think we assume `x.len() as u32` in runtime and then you can just `into()` it to `BalanceOf<T>`.

2020-09-29 13:18 UTC, kianenigma commented on frame/staking/src/lib.rs
> +			}) / BalanceOf::<T>::saturated_from(all.len() as u128)
i.e. 

```
```suggestion
			}) / BalanceOf::<T>::from(all.len() as u32)
```

2020-09-29 13:19 UTC, kianenigma commented on frame/staking/src/lib.rs
> +			}) / BalanceOf::<T>::saturated_from(all.len() as u128)
would be good to be safe against len == 0 as well.

2020-09-29 13:20 UTC, kianenigma commented on frame/staking/src/tests.rs
> +}
```suggestion
#[test]
fn maximum_validator_set() {
	ExtBuilder::default()
		.maximum_validator_count(4)
		.build()
		.execute_with(|| {
			assert_eq!(Staking::maximum_validator_count(), 4);
		});
}
```

superfluous, this is not testing the logic of the code, this is testing the setup of the tests.

2020-09-29 13:21 UTC, kianenigma commented on frame/staking/src/tests.rs
> +}
We have one test called `basic_setup_works()` or something along those lines in which you can test this.

2020-09-29 13:27 UTC, g2udevelopment commented
> I disagree with the logic of validator count update being baked into staking.
> 
> With `ValidatorCountAdjust `, you allow a user of substrate to opt out of this feature, which is good. But what if someone wants to have some update function, like the one proposed for kusama, but slightly different? this won't be possible with your API.
> 
> As recommended, I think having a `type ValidatorConvert: Convert<u32, u32>`. For a chain that wants to opt out, they will pass in an `IdentityConvert` which doesn't touch the count. Kusama can have its own custom implementation, and an other chain is free to customize this.

Sorry I missed the conversation about baking in the function in staking in the first commits. I think this is a good suggestion.

So I will remove the boolean flag , add the `Convert` type and provide both an Identity function and the current implementation. Then the Identity Implementation will serve as the `bool` false in the current implementation.

2020-09-29 13:29 UTC, kianenigma commented
> add the Convert type and provide both an Identity function. 

Yes, and this is already implemented in substrate 

https://github.com/paritytech/substrate/blob/4be954a8463e6f33e0ec854c4b8bcd940af260fc/primitives/runtime/src/traits.rs#L222-L226

So use this for identity.

2020-11-02 10:03 UTC, gnunicorn commented
Closed because it's been stale for a while.

2020-11-02 10:03 UTC, closed without merging