Release new version of wasm-builder-runner
paritytech/substrate pull request #7283
Opened 2020-10-08 20:59 UTC by bkchr

Besides the new version this merges `SKIP_WASM_BUILD` and
`BUILD_DUMMY_WASM_BINARY`, this means a file is generated with
`SKIP_WASM_BUILD` if no file existed before.

CC @xlc

2020-10-08 21:08 UTC, xlc commented
Should we bump major version? This is a breaking change. In last release dummy wasm build will generate wasm binary with non option type. The new version will make it option.

2020-10-08 21:48 UTC, bkchr commented
Yeah good point, I did not thought this trough and you are right.

2020-10-08 21:49 UTC, bkchr commented on utils/wasm-builder-runner/Cargo.toml
> +version = "1.0.7"
```suggestion
version = "2.0.0"
```

2020-10-08 22:24 UTC, andresilva requested changes
changes lgtm. we should also update the version in the crates that depend on this.

2020-10-08 22:24 UTC, andresilva commented on Cargo.lock
> +version = "1.0.7"
Needs to be updated.

2020-10-08 22:24 UTC, andresilva commented on utils/wasm-builder-runner/src/lib.rs
> +/// If `skip_build` is `true`, it will only generate the wasm binary if it doesn't exists.
```suggestion
/// If `skip_build` is `true`, it will only generate the wasm binary if it doesn't exist.
```

2020-10-09 08:48 UTC, andresilva approved these changes

2020-10-09 10:34 UTC, merged