Remove `RpcMetrics` weirdness
paritytech/substrate pull request #7608
Opened 2020-11-26 22:34 UTC by bkchr

The metrics was returning an error when prometheus was not given. This
was a really weird setup, especially when compared to all other metrics
that just do nothing if there is no registry.

2020-11-26 22:43 UTC, andresilva approved these changes

2020-11-26 22:47 UTC, andresilva requested changes
There is another `start_rpc_servers` for browser build that needs to be updated.

2020-11-27 08:58 UTC, tomaka approved these changes

2020-11-27 09:10 UTC, andresilva approved these changes

2020-11-27 09:10 UTC, andresilva commented
bot merge

2020-11-27 09:24 UTC, merged