Switch to use `diener patch` for companion build
paritytech/substrate pull request #8073
Opened 2021-02-08 14:14 UTC by bkchr

This switch to the new `diener patch` command to patch all Substrate
crates in Polkadot. This should remove the requirement to manually merge
Substrate master to make the companion build, as we now would use the
already with master merged code from this build job local checkout.

2021-02-09 15:18 UTC, andresilva approved these changes

2021-02-09 17:12 UTC, TriplEight requested changes
We already have `diener` [installed](https://github.com/paritytech/scripts/blob/master/dockerfiles/ci-linux/Dockerfile#L34) in the CI image. I suggest just bump the version there instead of installing it again, over and over.

2021-02-09 18:32 UTC, bkchr commented
> We already have `diener` [installed](https://github.com/paritytech/scripts/blob/master/dockerfiles/ci-linux/Dockerfile#L34) in the CI image. I suggest just bump the version there instead of installing it again, over and over.

Can we do this in a non-breaking way? The problem is that this new version isn't compatible with the old one. And I'm aware that we have installed it in the CI image. My idea was to update it here first, wait some days and update the CI image after this.

2021-02-10 08:44 UTC, gnunicorn approved these changes
lgtm

2021-02-10 11:38 UTC, merged

2021-02-10 17:05 UTC, TriplEight commented
> > We already have `diener` [installed](https://github.com/paritytech/scripts/blob/master/dockerfiles/ci-linux/Dockerfile#L34) in the CI image. I suggest just bump the version there instead of installing it again, over and over.
> 
> Can we do this in a non-breaking way? The problem is that this new version isn't compatible with the old one. And I'm aware that we have installed it in the CI image. My idea was to update it here first, wait some days and update the CI image after this.

CI image is updated every night (unless it's blocked by something else I.e. in substrate tests).
Ok, I got you, will do this after I'm back from vacation.