contracts: Use unstable sort for topics
paritytech/substrate pull request #8232
Opened 2021-03-01 11:47 UTC by athei

A contract can emit events with custom topics. Those topics are not allowed to be duplicates which is enforced by the supervisor. In order to do so those topics are sorted. This sort unnecessarily used a stable sorting algorithm. This PR replaces it by an unstable one which is faster and does not use additional memory.

2021-03-01 11:56 UTC, pepyakin requested changes
While sorting is deterministic, there is no guarantee that it will yield the same results across different platforms. 

Read my analysis [here](https://github.com/paritytech/substrate/pull/6754) under "word size differences"

2021-03-01 11:59 UTC, athei commented
I cannot find the analysis there. But point of the matter is that it does not need to be deterministic because we reject duplicates.

2021-03-01 12:02 UTC, pepyakin commented
Ok, right, sorry for my knee jerk reaction : )

That said, I am not sure if we still want to risk it, since the benefit doesn't seem to be that great. However, I can also accept this change if we put a giant banner that would scream that this is a dangerous piece of code and a proper description on why.

2021-03-01 12:07 UTC, athei commented
I just thought it was an oversight because the comments stated (no additional memory) but stable sorts do use additional memory. Yes, the gain is not big because the amount of topics is severely limited. However, I don't see the harm either. I moved the function closer to the place where it is used as a nested function. This way is is clear that it is only used there to de-duplicate topics.

2021-03-01 12:38 UTC, pepyakin approved these changes
Ok, I looked in the code and it seems fine now. However, now I realized that it was fine anyway. The items are just hashes and they are indistinguishable from each other. That is, if the hashes are [1, 2, 1] it doesn't matter if the result is [1, 1, 2] or [1, 1, 2].

I should've had a proper look at the very beginning, sorry for all the noise.

2021-03-01 12:58 UTC, ascjones approved these changes
LGTM

2021-03-02 07:26 UTC, athei commented
bot merge

2021-03-02 07:26 UTC, merged