Add a prefix to every log that occurs inside a future
paritytech/substrate pull request #8349
Opened 2021-03-12 17:41 UTC by cecton

This is a very small life improvement for sc-tracing that does 2 things:

1.  It adds a function `prefix_future_logs_with(prefix_string, future) -> prefixed_future` (I'm very bad at naming things so feel free to suggest me a better name :grin:) that allows the user to change the log prefixing of a future.

    This is handy in cumulus because some tasks (collation) are spawn in the background from polkadot but they really belong to the parachain. You can already do it without this helper but it requires a bit of knowledge on the internals.

    Normally you should use the macro `sc_tracing::logging::prefix_logs_with` but that macro works only as function decorator.

2.  I added a re-export of `tracing::Instrument` in `sc-tracing::Instrument`.

    The reasoning is that no matter what you do with sc-tracing, you might want to use this to preserve the spans you're in.

2021-03-16 13:56 UTC, mattrutherford approved these changes
LGTM - just curious, is there a reason that it's not required to use any other level than info?

2021-03-16 16:42 UTC, dvdplm approved these changes
Can you add a test for this as well please?

2021-03-16 19:31 UTC, bkchr requested changes
I still hope that we don't need this as discussed last week.

2021-03-17 08:23 UTC, cecton commented
> I still hope that we don't need this as discussed last week.

Yes I will check that out. Though I'm a bit afraid of doing magic with spans. It explodes to my face every time.

> Can you add a test for this as well please?

Ofc :sweat_smile: it was totally the plan.

> LGTM - just curious, is there a reason that it's not required to use any other level than info?

I think I copied the "info" from the previous implementation of telemetry. So it's more historical.

I don't think there is any impact on using info or something else. But I will check. It's not impossible that the span will be deactivated and the prefix won't work if you set the overall log level to something higher like warn or error.

2021-03-17 09:57 UTC, cecton commented
I'm closing this for now as @bkchr found a nice workaround: getting the current entered span, than re-adding it to the async task using `.instrument()`.

2021-03-17 09:57 UTC, closed without merging