Make pallet Assets instantiable
paritytech/substrate pull request #8483
Opened 2021-03-29 13:52 UTC by olanod

As mentioned in https://github.com/paritytech/substrate/issues/8453#issuecomment-809272236, making the assets pallet instantiable allows one to better group sets of assets that share something in common instead of putting everything in a single big group that might require some sort of filtering on the pallets that depend on some fungibles.

2021-03-29 14:14 UTC, shawntabrizi commented
@olanod asset creation is permissionless, so i don't see how such organization you are striving for will be enforced.

Do you have a more concrete idea on how you want to use this stuff?

2021-03-29 14:33 UTC, olanod commented
But it also can be permissioned only right? At least some of the assets in our chain will be created only by an authority i.e. a set of valid collaterals for a given stable coin. Also I'm looking into assets pallet mostly as an implementor of the `fungibles::*` traits and not much for its own dispatchable calls.

2021-03-29 14:56 UTC, shawntabrizi commented
@olanod no, it is current not possible to make it permissioned without some sort of wrapper on what functions can be called:

https://github.com/paritytech/substrate/blob/master/frame/assets/src/lib.rs#L368

2021-03-29 15:17 UTC, olanod commented
@shawntabrizi but that's fine no? I can have that wrapper as an extra pallet or a proxy that filters calls and still benefit from the instantiability of Assets pallet. I would say it's even more compelling to have different instances in this case, say I have one instance with some access control filter for cool people only and another one that is general purpose.

2021-04-02 18:19 UTC, shawntabrizi commented
@olanod please take a look at the diff that github provides. We do not use spaces in Substrate, so please  update them to tabs.

2021-04-02 19:46 UTC, olanod commented
My bad ... will have to disable the format on save 😅

2021-04-02 22:00 UTC, shawntabrizi approved these changes

2021-04-02 22:00 UTC, shawntabrizi commented
@thiolliere can you take a quick look here?

2021-04-02 22:00 UTC, olanod commented
The easiest way I found to revert the spaces formatting was to format again overriding the `hard_tabs` setting of rustfmt, rustmt has a lot of opinions on how the code should look like but as its not the scope of the PR I tried to leave out as much of the extra formatting that was not directly related to the feature as possible splitting chunks as far as `git add --patch --interactive` allowed me but there might be a bit of formatted code left here and there that I hope you wont mind(and might be for the best).

2021-04-13 09:49 UTC, thiolliere approved these changes

2021-04-13 09:49 UTC, thiolliere commented on frame/assets/src/lib.rs
> +				);
in substrate the line length is 100 character, those ensure doesn't need to go to newline.

2021-04-13 09:49 UTC, thiolliere commented on frame/assets/src/lib.rs
> +			);
same no need for new line

2021-04-13 09:49 UTC, thiolliere commented on frame/assets/src/lib.rs
> +			);
same

2021-04-13 11:21 UTC, thiolliere requested changes
ah I forgot, benchmarks need to be updated too, right now benchmark are only generated for default instance not for other ones.
```diff
diff --git a/frame/assets/src/benchmarking.rs b/frame/assets/src/benchmarking.rs
index 227d45623d..d02fe7b74b 100644
--- a/frame/assets/src/benchmarking.rs
+++ b/frame/assets/src/benchmarking.rs
@@ -135,7 +135,7 @@ fn assert_event<T: Config>(generic_event: <T as Config>::Event) {
        }));
 }
 
-benchmarks! {
+benchmarks_instance_pallet! {
        create {
                let caller: T::AccountId = whitelisted_caller();
                let caller_lookup = T::Lookup::unlookup(caller.clone());
```

But there will be other changes inside the file

2021-04-16 02:50 UTC, shawntabrizi commented
@thiolliere check again?

2021-04-16 08:51 UTC, thiolliere approved these changes
looks good to me

2021-04-16 08:51 UTC, thiolliere commented
bot merge

2021-04-16 08:51 UTC, merged

2021-04-16 09:36 UTC, olanod commented
Awesome! thanks @shawntabrizi was delaying that for the weekend 👍🏽