Disable logging in runtime when enabling `runtime-benchmarks`
paritytech/substrate pull request #8638
Opened 2021-04-19 11:13 UTC by athei

Fixes #8611

There is currently no way to compile out logging instructions from the wasm runtime without modifying `Cargo.toml` files. This caused to the situation in the linked issue.

In order to prevent such problems in the future we automatically deactivate logging when a runtime is being build for benchmarking. Please note that logs can still be emitted when benchmarking using the native runtime when necessary (during debugging for example).

2021-04-19 11:15 UTC, kianenigma commented
if correct, it should be fixed in polkadot runtimes as well.

2021-04-19 11:16 UTC, athei commented
> if correct, it should be fixed in polkadot runtimes as well.

Already on it.

2021-04-19 12:17 UTC, kianenigma commented
Then this is making a regression in all weights, right?

2021-04-19 12:17 UTC, kianenigma approved these changes

2021-04-19 13:06 UTC, athei commented
> Then this is making a regression in all weights, right?

I don't think so. It was only for one specific dispatchable in pallet_contracts which had a lot of `trace!` stuff in a tight loop.

2021-04-19 13:10 UTC, kianenigma commented
> > Then this is making a regression in all weights, right?
> 
> I don't think so. It was only for one specific dispatchable in pallet_contracts which had a lot of `trace!` stuff in a tight loop. But of course there are potentially more regressions which will be fixed by this.

phew, I thought we had artificially f-ed the weights in runtime v30, first version to have this feature.

2021-04-19 21:21 UTC, shawntabrizi approved these changes

2021-04-20 07:35 UTC, athei commented
@bkchr I moved the `disable-logging` flag to the `frame-benchmarking` crate (see latest changes in this PR) and it worked for me (the benchmarks do no longer log). Did you do something different [here](https://github.com/paritytech/polkadot/pull/2901#issuecomment-822779253)?

2021-04-20 07:44 UTC, bkchr commented
Yeah this works, but this also disables the logging for the node without benchmarking

2021-04-20 07:46 UTC, athei commented
> Yeah this works, but this also disables the logging for the node without benchmarking

`frame-benchmarking` is an optional dependency which is only there if the  `runtime-benchmarking` feature is set. So it should only disable logging when benchmarking is requested. Or am I missing something?

2021-04-20 07:55 UTC, bkchr commented
As I said in the polkadot pr, cargo and feature resolution is broken, since always

2021-04-20 08:08 UTC, athei commented
Yeah you are right. Just verified that behaviour. Rolling back the PR. I guess this is the best we can do right now.

2021-04-20 10:39 UTC, athei commented
The failing test parses logging output of node. Because all tests are run with the `runtime-benchmarks` feature enabled those fail because of missing output.

So automatically activating this feature on benchmarking does not seem to be a viable path, right?

2021-04-21 15:38 UTC, shawntabrizi requested changes
Not a fan of the new feature flag.

Should not possible that someone can compile their node for benchmarking and forget to disable logging such that their results are wrong.

Basti says:

> I think we can optimize this by introducing a new host function that returns the max log level. Than we could prevent so call into the host for every log line, which is very likely rejected on the host

2021-04-21 15:44 UTC, athei commented
Not sure how to progress without removing those tests then.

2021-04-22 05:36 UTC, bkchr commented
https://github.com/paritytech/substrate/pull/8655 this should fix it.

2021-04-22 13:39 UTC, athei commented
Superseded by https://github.com/paritytech/substrate/pull/8655

2021-04-22 13:39 UTC, closed without merging