[clippy] Fix clippy issues for crate sp-core
paritytech/substrate pull request #8809
Opened 2021-05-14 13:17 UTC by adoerr

Fix `clippy` issues for crate `sp-core`.  Running 

```
cargo +nightly clippy --all-targets -- -D warnings --no-deps
```
for the crate no longer produces any errors. 

I did allow some clippy checks, where a change would have impacted the function/method signature.

2021-05-14 15:16 UTC, bkchr requested changes
Please remove all these `clippy` attributes

2021-05-14 15:16 UTC, bkchr commented on primitives/core/benches/bench.rs
> +#![allow(deprecated)]
```suggestion
```

2021-05-14 15:16 UTC, bkchr commented on primitives/core/src/ed25519.rs
> +		matches!(public_key.verify(message.as_ref(), &sig), Ok(_))
```suggestion
		public_key.verify(message.as_ref(), &sig).is_ok()
```

2021-05-14 15:16 UTC, bkchr commented on primitives/core/src/lib.rs
> +	Error = 1_isize,
```suggestion
	Error = 1u8,
```

?

2021-05-14 15:16 UTC, bkchr commented on primitives/core/src/lib.rs
> +	Off = 0_isize,
Same

2021-05-14 15:16 UTC, bkchr commented on primitives/core/src/offchain/mod.rs
> +	PERSISTENT = 1_isize,
Same

2021-05-14 15:16 UTC, bkchr commented on primitives/core/src/offchain/mod.rs
> +	DeadlineReached = 1_isize,
Same.

2021-05-14 16:05 UTC, adoerr commented on primitives/core/src/lib.rs
> +	Error = 1_isize,
```
error[E0308]: mismatched types
   --> primitives/core/src/lib.rs:288:10
    |
288 |     Error = 1u8,
    |             ^^^ expected `isize`, found `u8`
    |
help: change the type of the numeric literal from `u8` to `isize`
    |
288 |     Error = 1isize,
    |             ^^^^^^
```
`u8` does not compile.

2021-05-14 16:21 UTC, adoerr commented
You mean all `#[allow(clippy::*)]` not only the `#[allow(deprecated)]`?

Frankly this defeats the whole purpose. If we still get `clippy` errors, the remaining changes a sort of superfluous. Allow some `clippy` checks at least documents, we are aware of the issue but overrule.

2021-05-14 19:33 UTC, bkchr commented
But we don't use clippy and also don't want to have these attributes in the code.

2021-05-14 19:34 UTC, bkchr commented on primitives/core/src/lib.rs
> +	Error = 1_isize,
Hmm okay.

2021-05-15 12:05 UTC, bkchr commented on primitives/core/benches/bench.rs
> +#[allow(clippy::clone_on_copy, clippy::ptr_arg)]
There are still attributes

2021-05-18 07:34 UTC, KiChjang approved these changes

2021-05-18 07:38 UTC, bkchr approved these changes

2021-05-18 07:38 UTC, merged