Update the Grafana dashboards
paritytech/substrate pull request #8832
Opened 2021-05-17 09:37 UTC by tomaka

Updates the dashboards to the latest changes that I've made over the past weeks.

As usual it's kind of hard to review if you're trying to read JSON, so I guess trust me that I haven't done anything wrong :shrug:

2021-05-17 09:40 UTC, lovelaced requested changes
There's a few specific node names in here which should either be removed or generalized in some way.

2021-05-17 09:48 UTC, tomaka commented
There were panels on top showing the node name, and apparently Grafana's export feature doesn't understand that the values come from a variable.

2021-05-17 09:49 UTC, lovelaced approved these changes

2021-05-17 15:20 UTC, adoerr approved these changes

2021-05-20 08:34 UTC, tomaka commented
bot merge

2021-05-20 08:34 UTC, merged