WIP Add option to specify if you want to run quick or long test for subst…
paritytech/substrate pull request #9133
Opened 2021-06-17 10:46 UTC by radupopa2010

Add the possibility to specify which kind of test to run for substrate. 
There are quick tests, like the ["smoke test"](https://gitlab.parity.io/parity/simnet/-/blob/master/testing/substrate_tests/tests/quick/001-smoketest.feature), or longer tests, like the ["load test"](https://gitlab.parity.io/parity/simnet/-/blob/master/testing/substrate_tests/tests/long/002-loadtest.feature)

For PRs we might want to run the quick tests, while for the nightly scheduled job the long test

2021-06-17 13:46 UTC, TriplEight requested changes
I think at this point it's already too much logic stored on the wrong side.
Besides, you have to maintain it in two repos, what if they will be more? And with this PR they will already be out of sync.
Most of this program has to reside within Simnet and CI should pass only variables depending on when it runs.

We've been discussing this before, we should stop triggering another CI from here and start passing instructions directly to Simnet.

2021-06-17 13:46 UTC, TriplEight commented on .gitlab-ci.yml
> +
```suggestion
```

2021-06-17 13:46 UTC, TriplEight commented on .maintain/gitlab/trigger_pipeline.sh
> +  while getopts c:u:r:i:n:g:f:t:r:a:s:h-: OPT; do
```suggestion
  while getopts f:r:a:c:t:u:r:i:n:g:s:h-: OPT; do
```

2021-06-17 14:01 UTC, radupopa2010 commented on .maintain/gitlab/trigger_pipeline.sh
> +  while getopts c:u:r:i:n:g:f:t:r:a:s:h-: OPT; do
you really like scrabble :))

2021-06-17 14:04 UTC, radupopa2010 commented
Yes, we need to schedule a meeting to speak how is better to implement the changes.

2021-06-17 14:48 UTC, TriplEight approved these changes

2021-07-19 09:30 UTC, TriplEight requested changes

2021-07-19 09:30 UTC, TriplEight commented on .gitlab-ci.yml
> +    - if [[ -v FEATURES && -n "${FEATURES}" ]]  ; then
It's better to just have a conditional flag in the script than writing additional scripts around it

2021-09-01 09:52 UTC, closed without merging