continue in pow loop instead of returning
paritytech/substrate pull request #9539
Opened 2021-08-11 12:05 UTC by OAyomide

It replaces the return statement with a continue, to prevent the node from terminating early. Fixes #9537

2021-08-11 12:11 UTC, seunlanlege requested changes
There are other return statements in the task, replace them with `continue`

2021-08-11 12:33 UTC, seunlanlege requested changes

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +				debug!(target: "pow", "SyncOracle is syncing.");
no need for this log line
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Unable to seal block");
also no need for this log line
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +				warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
this as well
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +				debug!(target: "pow", "Got the best hash");
double logs?
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
```suggestion
```

2021-08-11 12:33 UTC, seunlanlege commented on client/consensus/pow/src/lib.rs
> +					warn!(target: "pow", "Still waiting for seal for block {}", best_hash);
```suggestion
```

2021-08-11 13:33 UTC, seunlanlege approved these changes
Perfect

2021-08-11 13:34 UTC, seunlanlege commented
pinging @sorpaas @bkchr @gilescope

2021-08-11 17:21 UTC, bkchr approved these changes
Please format properly

2021-08-12 20:00 UTC, bkchr commented
CI fmt check is still not happy. You need to use `nightly` rustfmt.

2021-08-22 13:48 UTC, sorpaas approved these changes

2021-08-22 13:51 UTC, sorpaas approved these changes

2021-08-22 13:51 UTC, sorpaas commented
bot merge

2021-08-22 15:02 UTC, merged